import 'package:flutter/material.dart';
import '../constants/colors.dart';

class AIResponseCard extends StatelessWidget {
  final String aiAnswer;
  const AIResponseCard({Key? key, required this.aiAnswer}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(left: 16, top: 12),
      padding: EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: AppColors.askPageAIBackground,
        border: Border.all(color: AppColors.askPageAIBorder),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: AppColors.askPageAIBox,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  Icons.smart_toy,
                  size: 16,
                  color: AppColors.askPageAIBlue,
                ),
              ),
              SizedBox(width: 12),
              Text(
                'AI Response',
                style: TextStyle(
                  fontWeight: FontWeight.w500,
                  color: AppColors.askPageAIDarkBlue,
                ),
              ),
              SizedBox(width: 8),
              Icon(
                Icons.info_outline,
                size: 16,
                color: AppColors.askPageAIBlue,
              ),
            ],
          ),
          SizedBox(height: 12),
          Text(
            aiAnswer,
            style: TextStyle(
              fontSize: 14,
              color: AppColors.askPageAIText,
              height: 1.5,
            ),
          ),
          SizedBox(height: 12),
          Container(
            padding: EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppColors.askPageAIBox,
              border: Border.all(color: AppColors.askPageAIBorder),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Text(
              'This response was generated by trusted AI and may be reviewed later by a volunteer.',
              style: TextStyle(
                fontSize: 12,
                color: AppColors.askPageAINote,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
